### ISSUE TITLE
Does ME v0.5 support 3090 now?When I try to install it but I got an error:'Unsupported gpu archietecture'compute_86''

### ISSUE THREAD

**Issue by mrclovvn** [NVIDIA/MinkowskiEngine#282]
Hi @chrischoy 

I got a new 3090 recently but when I try to install the latest version of ME I encountered some problem.
It reported an error that:
 `nvcc fatal: Unsupported gpu architecture 'compute_86'` ,  
so I’m sorry to bother you here to confirm if it’s not supported 3090 yet?

And I have tried to set the variable as 
‘export TORCH_CUDA_ARCH_LIST="8.0" ’, 
then the ME can be installed successfully but I get a new error when I debug the FCGF benchmark_3dmatch.py:
`device-side assert triggered at /home/.../MinkowskiEngine-0.5/src/kernel_region.hpp:330`
in MinkowskiConvolution.py line 72.
However, the weird thing is if I just run benchmark_3dmatch.py  eveything is OK.

If you have any suggestions I would appreciate it.
Thank you.

**Comment by JohnRomanelis** [comment]
Hey @mrclovvn! I had the same error. The problem is with the cuda version you have. I suppose you have installed CUDA 11.0 as it is the latest version you see as an option when installing pytorch. I tried installing CUDA 11.1, then installing pytorch with cuda 11.0 and the problem is gone! I got some warnings during installation but i was able to install similar libraries that threw the same error.

**Comment by mrclovvn** [comment]
> Hey @mrclovvn! I had the same error. The problem is with the cuda version you have. I suppose you have installed CUDA 11.0 as it is the latest version you see as an option when installing pytorch. I tried installing CUDA 11.1, then installing pytorch with cuda 11.0 and the problem is gone! I got some warnings during installation but i was able to install similar libraries that threw the same error.

Thanks @JohnRomanelis! A few days ago when I saw README.md has updated the requirements about the supported CUDA version then I tried CUDA11.1, and there is indeed no any problem. The CUDA11.1 was not the supported version in the previous requirements, so I have not tried it before.
