### ISSUE TITLE
Error in MinkowskiChannelwiseConvolution layer

### ISSUE THREAD

**Issue by jethewes** [NVIDIA/MinkowskiEngine#299]
**Describe the bug**
When training a model using the `MinkowskiChannelwiseConvolution` layer with MinkowskiEngine v0.5, I see the following error during back-propagation:

```
Traceback (most recent call last):
  File "example.py", line 24, in <module>
    loss.backward()
  File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 233, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted (core dumped)
```

**To Reproduce**
The same github repository used to debug MinkowskiUnion in a previous issue – https://github.com/jethewes/minkowski-union-example . The previously commented-out MinkowskiChannelwiseConvolution layer has been reintroduced. This layer does not modify tensor shape, and when commented out, back-propagation is successful. The NVIDIA PyTorch Docker image at nvcr.io/nvidia/pytorch:20.12-py3 was used, with MinkowskiEngine v0.5 installed using pip.

**Expected behavior**
Successful back-propagation following loss calculation.

**Desktop (please complete the following information):**

NVIDIA PyTorch container `nvcr.io/nvidia/pytorch:20.12-py3` used.

Diagnostic output:
```
==========System==========
Linux-5.4.0-52-generic-x86_64-with-glibc2.10
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
==========Pytorch==========
1.8.0a0+1606899
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 450.80.02
CUDA Version 11.1
VBIOS Version 88.00.18.00.01
Image Version G503.0202.00.01
==========NVCC==========
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
==========CC==========
/usr/bin/c++
c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
0.5.0
MinkowskiEngine compiled with CUDA Support: True
NVCC version MinkowskiEngine is compiled: 11010
```

**Comment by chrischoy** [comment]
ME convolution does not use merge sort.

I suspect the error came from another layer.

Maybe related to this?

https://github.com/amdegroot/ssd.pytorch/issues/120#issuecomment-397492025

**Comment by jethewes** [comment]
I greatly simplified the example (see my new commit) to a three-layer model with a convolution layer, a global pooling layer then a linear layer. I try four different permutations, swapping between `MinkowskiConvolution` and `MinkowskiChannelwiseConvolution`, and also swapping between `MinkowskiGlobalPooling` and a custom layer which uses `torch.nn.AdaptiveMaxPool1d` on the feature tensor. I find that `MinkowskiConvolution` succeeds with either pooling method, while `MinkowskiChannelwiseConvolution` throws the above error regardless of pooling method.

The channelwise layer does seem to be the common factor – is it possible it's causing some subtle problem which only triggers an error further down the line?

**Comment by chrischoy** [comment]
I cannot reproduce the error on pytorch 1.7.

```
==========System==========
Linux-5.4.0-62-generic-x86_64-with-glibc2.10
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
==========Pytorch==========
1.7.0
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 450.102.04
CUDA Version 11.0
VBIOS Version 90.02.2E.00.0C
Image Version G001.0000.02.04
==========NVCC==========
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
==========CC==========
/usr/bin/c++
c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
0.5.0
MinkowskiEngine compiled with CUDA Support: True
NVCC version MinkowskiEngine is compiled: 11010
CUDART version MinkowskiEngine is compiled: 11010
```

I noticed that you are using the pytorch nightly version (currently 1.8). Can you try pytorch 1.7 instead?

**Comment by jethewes** [comment]
I tried with Pytorch 1.7 and see the same error. I used the standard `1.7.0-cuda11.0-cudnn8-devel` PyTorch docker image – here are the diagnostics:

```
==========System==========
Linux-5.4.0-52-generic-x86_64-with-glibc2.10
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0]
==========Pytorch==========
1.7.0
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 450.80.02
CUDA Version 11.0
VBIOS Version 88.00.18.00.01
Image Version G503.0202.00.01
==========NVCC==========
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
==========CC==========
/usr/bin/c++
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
0.5.0
MinkowskiEngine compiled with CUDA Support: True
NVCC version MinkowskiEngine is compiled: 11000
CUDART version MinkowskiEngine is compiled: 11000
```

**Comment by chrischoy** [comment]
Thanks, that is very strange.

I was able to reproduce the error on `nvcr.io/nvidia/pytorch:20.12-py3`.
However, when I created a new conda environment in the same docker with pytorch 1.7, I was able to run the `example.py` without any errors.

In the  `nvcr.io/nvidia/pytorch:20.12-py3` image

```
yes | conda create -p /tmp/test python=3.8    # yes to all and create env on /tmp/test
. /opt/conda/etc/profile.d/conda.sh                 # init conda in the current shell
conda activate /tmp/test
conda install pytorch -c pytorch
pip install -U git+https://github.com/NVIDIA/MinkowskiEngine --no-deps -v
```

Once you follow this on the `nvcr.io/nvidia/pytorch:20.12-py3` image, you should see

```
python -c "import MinkowskiEngine as ME; ME.print_diagnostics()"

==========System==========
Linux-4.15.0-15-generic-x86_64-with-glibc2.10
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
==========Pytorch==========
1.7.1
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 440.64.00
CUDA Version 11.1
VBIOS Version 88.00.4F.00.08
Image Version G503.0240.00.02
==========NVCC==========
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
==========CC==========
/usr/bin/c++
c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
0.5.0
MinkowskiEngine compiled with CUDA Support: True
NVCC version MinkowskiEngine is compiled: 11010
CUDART version MinkowskiEngine is compiled: 11010
```

I could successfully run `example.py` without a problem.

**Comment by chrischoy** [comment]
Another bug report that got the same error https://github.com/NVIDIA/MinkowskiEngine/issues/283. This also happens with pytorch 1.7 with CUDA 11.0. The error is fixed resolved with CUDA 11.1 with torch 1.7.

**Comment by jethewes** [comment]
Thank you for your help! Your suggestion for a workaround worked for me – I've moved to a container with CUDA 11.1 and torch 1.7, and I no longer see any problems.

**Comment by Eaphan** [comment]
I have the same error too when I use the MinkowskiEngine with tag v0.5.4.
Then I checkout commit 02fc608bea4c0549b0a7b00ca1bf15dee4a0b228 and re-install the MinkowskiEngine, and the error disappears.
