### ISSUE TITLE
Function ME.utils.sparse_quantize causes memory leak

### ISSUE THREAD

**Issue by lilanxiao** [NVIDIA/MinkowskiEngine#411]
**Describe the bug**
The `ME.utils.sparse_quantize` function seems to cause a slow memory leak. The RAM (not GPU RAM) usage increases gradually and ends up with OOM in a long training schedule. 

When the following code runs, the RAM usage increases slowly. This code prints the percentage of RAM usage. You need to wait for a while to see the difference (15~20 minutes should be enough). Note that this code monitor the RAM usage of the entire system, you should not manipulate your computer when it runs. 

Here I use Dataloader to accelerate the process. But you can reproduce this behavior without the Dataloader (i.g. iterate through the dataset directly). 

************************************************************************************
**To Reproduce**

```
import MinkowskiEngine as ME
import numpy as np
import psutil
import os
from torch.utils.data import DataLoader, Dataset


def main():
    ITERS = 100000
    BS = 8
    ds = FooDataset(size=ITERS*BS, num_pts=100000)
    dl = DataLoader(ds, batch_size=BS, num_workers=8, shuffle=True)
    for i, data in enumerate(dl):
        if i % 100 == 0:
            print("{:d}, memory used:".format(i), psutil.virtual_memory()[2])


class FooDataset(Dataset):
    def __init__(self, size, num_pts) -> None:
        super().__init__()
        self.num_pts = int(num_pts)
        self.size = int(size)
    
    def __len__(self):
        return self.size
    
    def __getitem__(self, index):
        coords = np.random.rand(self.num_pts, 3) * np.random.randint(1, 10)
        feats = np.random.rand(self.num_pts, 3) * np.random.randint(1, 10)
        # NOTE: the RAM usage increases slower if data has smaller variance
        # coords = np.random.rand(self.num_pts, 3)
        # feats = np.random.rand(self.num_pts, 3)
        vox, feats = ME.utils.sparse_quantize(coords, feats, quantization_size=0.02)
        vox = vox.numpy()
        feats = feats + 0.1
        return vox[:10, ...], feats[:10, ...]


if __name__ == "__main__":
    main()

```
On my machine with 32GB RAM, the RAM usage linearly increases when this code runs. The RAM usage is related to the variance of data. A larger variance brings a faster usage increase. For instance, you see a slower increase with the two commented lines. If I use real point clouds instead of random numbers, the code can reach OOM if runs for an extremely long time. 

************************************************************************************
**Expected behavior**
The RAM usage is steady. 

************************************************************************************
**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04
 - Python version: 3.7.10
 - Pytorch version: 1.8.1
 - CUDA version: 10.2
 - NVIDIA Driver version: 470.63
 - Minkowski Engine version: 0.5.4
 - Output of the following command. (If you installed the latest MinkowskiEngine, paste the output of `python -c "import MinkowskiEngine as ME; ME.print_diagnostics()"`. Otherwise, paste the output of the following command.)
==========System==========
Linux-5.4.0-87-generic-x86_64-with-debian-buster-sid
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0]
==========Pytorch==========
1.8.1
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 470.63.01
CUDA Version 11.4
VBIOS Version 90.04.76.40.91
Image Version G001.0000.02.04
GSP Firmware Version N/A
==========NVCC==========
/usr/local/cuda-10.2/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
==========CC==========
/usr/bin/c++
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
==========MinkowskiEngine==========
0.5.4
MinkowskiEngine compiled with CUDA Support: True
NVCC version MinkowskiEngine is compiled: 10020
CUDART version MinkowskiEngine is compiled: 10020

************************************************************************************
**Additional context**
The memory leak comes probably from the C/C++ extension side, as I cannot trace it with [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) from the Python side.

**Comment by lilanxiao** [comment]
For those who encounter the same OOM problem: 

use
```
vox = np.floor(coords/0.02).astype(np.int32)
index, _ = ME.utils.quantization.quantize(vox)
vox = vox[index]
feats = feats[index]
```
instead of
```
vox, feats = ME.utils.sparse_quantize(coords, feats, quantization_size=0.02)
```
Then the OOM problem is gone. The result is the same. But I'm still not sure if this is the intended behavior of sparse_quantize or a bug. I let this issue open.

**Comment by kochsebastian** [comment]
@lilanxiao I cannot reproduce the issue with your code but I also observed extensive memory leakage with my current code. However I could not pinpoint the root cause yet. I am still looking into what could cause this memory leakage.
